//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vn_post_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public int id_category { get; set; }
        public Nullable<int> id_sort { get; set; }
        public string category1 { get; set; }
    }
}
