//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vn_post_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sort
    {
        public int id { get; set; }
        public string sort1 { get; set; }
    }
}
